# Generated by Django 3.0.8 on 2020-09-20 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico_dispenser', models.CharField(max_length=30)),
                ('date_time', models.CharField(max_length=20)),
                ('battery_level', models.IntegerField()),
                ('paper_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ident_dispenser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico_dispenser', models.CharField(max_length=50)),
                ('client_id_mqtt', models.CharField(max_length=30)),
                ('localizacao', models.CharField(max_length=200)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
