# Generated by Django 3.0.8 on 2020-09-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ident_dispenser',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='ident_dispenser',
            name='id_usuario_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ident_dispenser',
            name='localizacao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
