# Generated by Django 3.0.8 on 2020-10-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200924_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_pacotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico_dispenser', models.CharField(max_length=30)),
                ('date_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ident_dispenser',
            name='paper_level_last',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ident_dispenser',
            name='porcentagem_acumulada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ident_dispenser',
            name='relacao_pacotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ident_dispenser',
            name='ultima_atualizacao',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
